# Generated by Django 4.2 on 2024-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
