# Generated by Django 4.2 on 2023-11-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellatutors_web', '0002_order_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
