# Generated by Django 4.2 on 2023-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellatutors_web', '0003_user_is_new_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Order Created', 'New Order Created'), ('Order Approved', 'Order Approved'), ('Account Creation', 'Account Creation'), ('Account Approval', 'Account Approval')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
    ]
