# Generated by Django 4.2 on 2023-11-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellatutors_web', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_seen_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_seen_by_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
